packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: false
  opensrc: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - effect@4.0.0-beta.85
  - '@effect/platform-node-shared@4.0.0-beta.85'
  - '@effect/platform-node@4.0.0-beta.85'
